# Generated by Django 5.1.3 on 2024-11-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activated_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
